// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: all.sql

package newmodels

import (
	"context"
)

const truncate = `-- name: Truncate :exec
DELETE FROM archived_jobs
`

func (q *Queries) Truncate(ctx context.Context) error {
	_, err := q.exec(ctx, q.truncateStmt, truncate)
	return err
}
