// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package newmodels

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/kevinburke/go-types"
)

type ArchivedJobStatus string

const (
	ArchivedJobStatusSucceeded ArchivedJobStatus = "succeeded"
	ArchivedJobStatusFailed    ArchivedJobStatus = "failed"
	ArchivedJobStatusExpired   ArchivedJobStatus = "expired"
)

func (e *ArchivedJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArchivedJobStatus(s)
	case string:
		*e = ArchivedJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ArchivedJobStatus: %T", src)
	}
	return nil
}

type NullArchivedJobStatus struct {
	ArchivedJobStatus ArchivedJobStatus
	Valid             bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArchivedJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ArchivedJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArchivedJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArchivedJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.ArchivedJobStatus, nil
}

type DeliveryStrategy string

const (
	DeliveryStrategyAtMostOnce  DeliveryStrategy = "at_most_once"
	DeliveryStrategyAtLeastOnce DeliveryStrategy = "at_least_once"
)

func (e *DeliveryStrategy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryStrategy(s)
	case string:
		*e = DeliveryStrategy(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryStrategy: %T", src)
	}
	return nil
}

type NullDeliveryStrategy struct {
	DeliveryStrategy DeliveryStrategy
	Valid            bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryStrategy) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryStrategy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryStrategy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryStrategy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.DeliveryStrategy, nil
}

type JobStatus string

const (
	JobStatusQueued     JobStatus = "queued"
	JobStatusInProgress JobStatus = "in-progress"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus
	Valid     bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.JobStatus, nil
}

type ArchivedJob struct {
	ID        types.PrefixUUID  `json:"id"`
	Name      string            `json:"name"`
	Attempts  int16             `json:"attempts"`
	Status    ArchivedJobStatus `json:"status"`
	CreatedAt time.Time         `json:"created_at"`
	Data      json.RawMessage   `json:"data"`
	ExpiresAt types.NullTime    `json:"expires_at"`
	AutoID    int64             `json:"auto_id"`
}

type Job struct {
	Name             string           `json:"name"`
	DeliveryStrategy DeliveryStrategy `json:"delivery_strategy"`
	Attempts         int16            `json:"attempts"`
	Concurrency      int16            `json:"concurrency"`
	CreatedAt        time.Time        `json:"created_at"`
	AutoID           int64            `json:"auto_id"`
}

type QueuedJob struct {
	ID        types.PrefixUUID `json:"id"`
	Name      string           `json:"name"`
	Attempts  int16            `json:"attempts"`
	RunAfter  time.Time        `json:"run_after"`
	ExpiresAt types.NullTime   `json:"expires_at"`
	CreatedAt time.Time        `json:"created_at"`
	UpdatedAt time.Time        `json:"updated_at"`
	Status    JobStatus        `json:"status"`
	Data      json.RawMessage  `json:"data"`
	AutoID    int64            `json:"auto_id"`
}
